### ISSUE TITLE
EFS Encyption

### ISSUE THREAD

**Issue by hhettiarachchi** [aws-quickstart/quickstart-atlassian-crowd#29]
It seems like none of the Atlassian software is using encryption at rest for file share (Encrypted EFS) with Quickstart. This would be beneficial to enable in terms of security. However, there's an encryption option already in place for the RDS services.

**Comment by tonynv** [comment]
@dylanrathbone

**Comment by tonynv** [comment]
@nanux  Thoughts on this enhancement request ?

**Comment by nanux** [comment]
Hi @hhettiarachchi, thanks for the feedback. We were actually looking into introducing encryption but due to problems with the backwards compatibility of that change, we have decided to not merge it as it could disrupt existing stacks.

It is not a complicated change if you are willing to apply it to your deployment. We have PR in our fork where most of the work is first reviewed. You can see the necessary modifications you need to apply to the templates to enable encryption.

PR with encryption:
https://github.com/atlassian/quickstart-atlassian-crowd/pull/62/files#diff-5056f98d7efbb39e1b074a5600a6034c3697db21602eb9c9d590fe779ec1ed21
